### PR TITLE
Add filterset_class to DjangoObjectType

### PR DESCRIPTION
**Pull request by leiserfg**
Solves #22 it's a way of v.g: adding django-watson as a filter (It's the reason i did it 😄 )

### CODE REVIEW

**Comment by eamigo86** [comment]
Hi @leiserfg, could you give me an example of how you use django-watson as a filtering engine?

**Comment by leiserfg** [comment]
Something like this:
```python
import django_filters
from watson.search import filter

class SearchFilter(django_filters.FilterSet):
    search = django_filters.CharFilter('search', method='search')

    def search(self, queryset, name, value):
        return filter(queryset, value)
```
and then in the DjangoObjectType

````
class Cosa(DjangoObjectType):
  class Meta:
    filterset_class =  SearchFilter
```

Maybe it'll need some tweaks but no too much 'cause watson is very generic once you have the models registred.

**Comment by eamigo86** [comment]
ok, and how you define your schema for "Cosa"?

**Comment by leiserfg** [comment]
O sorry, i forgot the model:
```python
class Cosa(DjangoObjectType):
  class Meta:
    model = CosaModel
    filterset_class =  SearchFilter
```
*Cosa* is a model, replace it for User or whatever you want.

**Pull request merged**
