### PR TITLE
Improve project quality checks

### PR DESCRIPTION
**Pull request by eclar**
Project:
- Removed support for python<3.6 from classifiers
- Added poetry package management
- Added dev dependencies in poetry
- Added black, coverage, travis badges to README
- Compatible with Travis and coverage.io

Testing:
- Removed testing project and added tests folder
- Tests are now using pytest with the appropriate configuration
- Added tox for testings purposes
- Added quality checks
- Added coverage

Quality:
- Added linters
- Blacked project

I was to lazy to write more tests and you don't have to merge the whole PR but at least adding the testing with travis and the coverage would be awesome I think.

You can see an example here: https://travis-ci.org/eclar/graphene-django-extras

### CODE REVIEW

**Comment by eamigo86** [comment]
Hi @eclar, thanks for this work. I appreciate it so much. It will be great help

**Comment by eclar** [comment]
Hi @eamigo86, if you want to use fully the PR, you should set up a travis and a coverage.io project :)

**Comment by eamigo86** [comment]
Hello, excuse my ignorance, but you could help me set up a travis and a coverage.io project for the package.
If you can, tell me what you need from me.
Thanks in advance

**Comment by eclar** [comment]
Create accounts here: https://travis-ci.org/ and https://codecov.io/ with your github account and create a project for graphene-django-extras on both sites. The rest should sort of just work.

**Pull request merged**
